### ISSUE TITLE
Decryption method

### ISSUE THREAD

**Issue by atefm** [HaoLiuHust/caffe_model_encrypt#1]
The suggested decryption method does not work and causes an error. The correct method is the following:

shared_ptr<Net> net_ptr;
std::string pwd="my_encrypt_path";

NetParameter proto;
caffe_encrypt::decrypt_proto(protopath,pwd,proto);//decrypt proto
proto.mutable_state()->set_phase(caffe::TEST);
net_ptr.reset(new Net(proto));

NetParameter modelparams;
caffe_encrypt::decrypt_binary(modelpath,pwd,modelparams);//decrypt params

net_ptr->CopyTrainedLayersFrom(modelparams);

**Comment by HaoLiuHust** [comment]
I am using nvcaffe as the framework, maybe this cause the different
